[package]
name = "hifive"
version = "0.1.0"
repository = "https://github.com/dvc94ch/hifive"
authors = ["David Craven <david@craven.ch>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Board support crate for hifive and lofive boards."
keywords = ["riscv", "register", "peripheral"]
license = "ISC"

[dependencies]
riscv = { path = "../riscv" }
riscv-rt = { path = "../riscv-rt" }
e310x-hal = { path = "../e310x-hal", features = ["pll", "hfxosc", "lfaltclk"] }
