[package]
name = "hifive1"
version = "0.5.0"
repository = "https://github.com/riscv-rust/hifive1"
authors = ["David Craven <david@craven.ch>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Board support crate for HiFive1 and LoFive boards"
keywords = ["riscv", "register", "peripheral"]
license = "ISC"
edition = "2018"

[dependencies]
e310x-hal = "0.5.0"
embedded-hal = "0.2.3"

[features]
board-hifive1 = []
board-hifive1-revb = ["e310x-hal/g002"]
board-lofive = []

[package.metadata.docs.rs]
features = ['board-hifive1-revb']
